<img src="img/Recurso-26.png" width="200">

# 01MIAR  - Estructuras de datos, +Pandas

![logo](img/python_logo.png)

**Nombre:** Evelyn Lascano<br>
**Fecha:** 10/02/2026

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.3'

## Operaciones en pandas
### Búsqueda

In [4]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  2  2  5
1  2  2  1

In [5]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [6]:
# buscando valores
display(frame.isin([3,2])) # --> mask de respuesta (valores que son 3 o 2)

      A     B      C
0  True  True  False
1  True  True  False

In [7]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4])) #devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values) # pandas es una capa alrededor de numpy

0

       A      B      C
0  False  False  False
1  False  False  False

[[False False False]
 [False False False]]

numpy.ndarray

In [8]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

5

      A     B      C
0  True  True   True
1  True  True  False

### Ordenación

In [9]:
from random import shuffle
rand_matrix = np.random.randint(20,size=(5,4))
indices = list(range(5))
shuffle(indices) # mezcla indices
frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D   A   C   B
3   7  16  17   8
0  18  13   2  17
2   0   6  18   6
1   9  10  18   5
4   2  17  10  15

In [10]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D   A   C   B
4   2  17  10  15
3   7  16  17   8
2   0   6  18   6
1   9  10  18   5
0  18  13   2  17

    D   A   C   B
3   7  16  17   8
0  18  13   2  17
2   0   6  18   6
1   9  10  18   5
4   2  17  10  15

In [11]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B   A
3   7  17   8  16
0  18   2  17  13
2   0  18   6   6
1   9  18   5  10
4   2  10  15  17

In [12]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D   A   C   B
2   0   6  18   6
1   9  10  18   5
0  18  13   2  17
3   7  16  17   8
4   2  17  10  15

In [13]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    B   D   A   C
3   8   7  16  17
0  17  18  13   2
2   6   0   6  18
1   5   9  10  18
4  15   2  17  10

In [14]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D   A   C   B
4   2  17  10  15
3   7  16  17   8
0  18  13   2  17
1   9  10  18   5
2   0   6  18   6

### Ranking
* Construir un ranking de valores

In [15]:
display(frame)

    D   A   C   B
4   2  17  10  15
3   7  16  17   8
0  18  13   2  17
1   9  10  18   5
2   0   6  18   6

In [16]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
4  1.0  4.0  2.0  3.0
3  1.0  3.0  4.0  2.0
0  4.0  2.0  1.0  3.0
1  2.0  3.0  4.0  1.0
2  1.0  3.0  4.0  3.0

In [18]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
     print(x)

18
18
17
10
2

## Operaciones
* Operaciones matemáticas entre objetos

In [19]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  45  80  11   7
1  39  78  98  38
2  96  28  83  68
3  34  80   7  21

    0   1   2   3
0  10  13  68  10
1  93  79  49  20
2  44  79  53  62
3  53  14  95  82

In [20]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0   55   93   79   17
1  132  157  147   58
2  140  107  136  130
3   87   94  102  103

In [21]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0 -35 -67  57   3
1  54   1 -49 -18
2 -52  51 -30  -6
3  19 -66  88  61

In [22]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  45  80  11   7
1  39  78  98  38
2  96  28  83  68
3  34  80   7  21

    0   1   2
0  85  90  97
1  31  72  69
2   0  12  13

       0      1      2   3
0  130.0  170.0  108.0 NaN
1   70.0  150.0  167.0 NaN
2   96.0   40.0   96.0 NaN
3    NaN    NaN    NaN NaN

In [23]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1      2     3
0  130.0  170.0  108.0   7.0
1   70.0  150.0  167.0  38.0
2   96.0   40.0   96.0  68.0
3   34.0   80.0    7.0  21.0

Operadores aritméticos solo válidos en elementos aceptables

In [25]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [26]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)
display(df.iloc[0])
display(type(df.iloc[0]))
# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))
# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  5  8  5  1
1  2  2  8  0
2  3  4  2  4

A    5
B    8
C    5
D    1
Name: 0, dtype: int32

pandas.core.series.Series

   A  B  C  D
0  0  0  0  0
1 -3 -6  3 -1
2 -2 -4 -3  3

   A  B  C  D
0  0  0  0  0
1 -3 -6  3 -1
2 -2 -4 -3  3

   A  B  C  D
0  0  3  0 -4
1  0  0  6 -2
2  0  1 -1  1

pandas se basa en NumPy, np operadores binarios y unarios son aceptables
### Operaciones Unarias (Element-wise)
| Tipo | Operación | Descripción |
| :--- | :--- | :--- |
| **Unario** | `abs` | Valor absoluto de cada elemento |
| | `sqrt` | Raíz cuadrada de cada elemento |
| | `exp` | $e^x$, siendo $x$ cada elemento |
| | `log`, `log10`, `log2` | Logaritmos en distintas bases de cada elemento |
| | `sign` | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | `ceil` | Redondea cada elemento hacia arriba (al entero superior) |
| | `floor` | Redondea cada elemento hacia abajo (al entero inferior) |
| | `isnan` | Retorna un booleano indicando si el elemento es NaN |
| | `cos`, `sin`, `tan` | Operaciones trigonométricas en cada elemnto |
| | `arccos`, `arcsin`, `arctan` | Inversas de operaciones trigonométricas en cada elemento|
| **Binario** | `add` | Suma de dos arrays ($a + b$) |
| | `subtract` | Resta de dos arrays ($a - b$) |
| | `multiply` | Multiplicación de dos arrays ($a * b$) |
| | `divide` | División de dos arrays ($a / b$) |
| | `maximum`, `minimum` | Retorna el valor máximo o mínimo de cada pareja de elementos |
| | `equal`, `not_equal` | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | `greater`, `greater_equal`,`less`, `less_equal` | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

Aplicación de funciones a medida con lambda

In [27]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por columna

   A  B  C  D
0  8  4  3  4
1  4  9  8  9
2  6  8  7  1

0    5
1    5
2    7
dtype: int64

In [28]:
def max_min(x):
 return x.max() - x.min()
print(frame.apply(max_min, axis = 0)) # diferencia por columna

A    4
B    5
C    5
D    8
dtype: int64

In [29]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1)) # diferencia por fila

   A  B  C  D
0  0  4  3  5
1  4  2  9  7
2  2  7  1  5

0    5
1    7
2    6
dtype: int64

## Estadística descriptiva
* Análisis preliminar de los datos
* Para Series y DataFrame

### Estadísticas Descriptivas y de Agregación
| Operación | Descripción |
| :--- | :--- |
| `count` | Número de valores no NaN |
| `describe` | Conjunto de estadísticas sumarias (media, std, min, max, etc.) |
| `min`, `max` | Valores mínimo y máximo |
| `argmin`, `argmax` | Índices posicionales del valor mínimo y máximo |
| `idxmin`, `idxmax` | Índices semánticos del valor mínimo y máximo |
| `sum` | Suma de los elementos |
| `mean` | Media aritmética de los elementos |
| `median` | Mediana de los elementos |
| `mad` | Desviación absoluta media del valor medio |
| `var` | Varianza de los elementos |
| `std` | Desviación estándar de los elementos |
| `cumsum` | Suma acumulada de los elementos |
| `diff ` | Diferencia aritmética de los elementos |

In [31]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"], "edad" : [34,35,37,40],"puntos" : [98,12,98,np.nan], "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe()) # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    35    12.0      F
2  Manuel    37    98.0      M
3  Carlos    40     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   36.500000  69.333333
std     2.645751  49.652123
min    34.000000  12.000000
25%    34.750000  55.000000
50%    36.000000  98.000000
75%    37.750000  98.000000
max    40.000000  98.000000

In [32]:
# operadores básicos
print(frame.sum())
display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          146
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    35    12.0      F
2  Manuel    37    98.0      M
3  Carlos    40     NaN      M

0    132.0
1     47.0
2    135.0
3     40.0
dtype: float64

In [33]:
frame.mean(numeric_only=True)

edad      36.500000
puntos    69.333333
dtype: float64

In [34]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    69   110.0     FF
2        MarisaLauraManuel   106   208.0    FFM
3  MarisaLauraManuelCarlos   146     NaN   FFMM

In [35]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [36]:
print(frame['edad'].std())

2.6457513110645907

In [37]:
frame['edad'].idxmax()

3

In [38]:
frame['puntos'].idxmin()

1

In [39]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())
display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    37    98.0      M

In [40]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [41]:
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    35    12.0      F      1.0
2  Manuel    37    98.0      M      3.0
3  Carlos    40     NaN      M      NaN

## Agregaciones

In [42]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    35    12.0      F      1.0
2  Manuel    37    98.0      M      3.0
3  Carlos    40     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [43]:
# si es Nan descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [44]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.5    55.0      2.0
M       38.5    98.0      3.0

In [45]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    35    98.0      3.0
M       Manuel    40    98.0      3.0

In [50]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max'])) #faltan datos preguntar

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.5  35   12.0  55.0  98.0
M        37  38.5  40   98.0  98.0  98.0

In [51]:
# Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
 return x["edad"].mean() > 30
display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    35    12.0      F      1.0
2  Manuel    37    98.0      M      3.0
3  Carlos    40     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    35    12.0      F      1.0
2  Manuel    37    98.0      M      3.0
3  Carlos    40     NaN      M      NaN

## Correlaciones
pandas incluye métodos para analizar correlaciones
* Relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación)
* obj.corr(obj2) --> medida de correlación entre los datos de ambos objetos
* https://blogs.oracle.com/ai-and-datascience/post/introduction-to-correlation
## Ejemplo Fuel efficiency
https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [53]:
import pandas as pd
path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg'
mpg_data = pd.read_csv(path, sep='\s+', header=None,
 names = ['mpg', 'cilindros', 'desplazamiento','potencia',
 'peso', 'aceleracion', 'año', 'origen', 'nombre'],
 na_values='?', engine='c')

HTTPError: HTTP Error 404: Not Found

In [ ]:
display(mpg_data.sample(5))

In [ ]:
display(mpg_data.describe(include='all'))