## PAO25_25_07_Python_Pandas
### 0.1 PAO 25-25- Pandas
![logo](img/python_logo.png)
**Nombre del programadoe:** Evelyn Lascano<br>
**Fecha:** 06/02/2026

## 1 Pandas
* Librería (de facto estándar) para estructurar datos tabulares<br>
* Multivariable (string, int, float, bool…)
* Dos clases:
    * Series (1 dimensión)
    * DataFrames (2+ dimensiones)

In [ ]:
 # librería externa
import pandas as pd
from pandas import Series, DataFrame

In [ ]:
 pd.__version__

## 2 Series
* Datos unidimensionales (similar a NumPy)<br>
* Elementos + índices modificables

In [ ]:
countries = pd.Series(['Spain','Andorra','Gibraltar','Portugal','France'])
print(countries)

In [ ]:
# especificando el índice
countries = pd.Series(['Spain','Andorra','Gibraltar','Portugal','France'],
index=range(10,60,10))
print(countries)

In [ ]:
  # los índices pueden ser de más tipos
football_cities = pd.Series(['Barcelona','Madrid','Valencia','Sevilla'],
index=['a','b','c','d'])
print(football_cities)

In [ ]:
 # Atributos
football_cities.name = 'Ciudades con dos equipos en primera' # nombrar la Serie
football_cities.index.name = 'Id' # Describir los índices
print(football_cities)

In [ ]:
# 1. acceso por posicion (solucion al error)
#usamos.iloc para indicar que queremos el tercer elemento  (indice 2)
print(f"posicion (indice 2): {football_cities.iloc[2]}")

#2.Acceso por ETIQUETA SEMANTICA
# usamos . loc para indicar que buscamos la etiqueta ['c']})
print(f"por etiqueta ('c'): {football_cities.loc['c']}")

#3: comparacion logica correcta
print(f"¿son iguales?: {football_cities.loc['c']==football_cities.iloc[2]}")

## 3 Tratamiento similar a ndarray

In [ ]:
# múltiple recolección de elementos
print(football_cities[ ['a','c'] ])
print(football_cities.iloc[ [0, 3] ])  #devuelve las posiciones como al inicio del ejercicio

In [ ]:
 # slicing
print(football_cities[:'c']) # incluye ambos extremos con el indice semantico
print(football_cities[:2]) #Depende de los indices de los números

In [ ]:
#cast a list
lista = list(football_cities[:'c'])
print(lista)
print(type(lista))

In [ ]:
 type(football_cities[:'c'])

In [ ]:
 #cast a ndarray
import numpy as np
cities = np.array(football_cities[:'c'])
print(cities)
print(type(cities))

In [ ]:
 # cas a dictionary
lista = dict(football_cities[:'c']) #buscar clave y valor
print(lista)

In [ ]:
# uso de masks para seleccionar
fibonacci = pd.Series([0, 1, 1, 2, 3, 5, 8, 13, 21])
print(fibonacci)
mask = fibonacci > 10
print(mask)
print(fibonacci[mask])
dst = pd.Series([13,21])
print(dst)
dst.equals(fibonacci)
fb = fibonacci[mask]
fb.reset_index(drop=True, inplace=True)
print(fb)
dst.equals(fb) #Para el valor que se obtiene

In [ ]:
# aplicar funciones de numpy a la serie
import numpy as np
print(np.sum(fibonacci))

In [ ]:
 #filtrado con np.where
distances = pd.Series([12.1,np.nan,12.8,76.9,6.1,7.2])
valid_distances = np.where(pd.notnull(distances),distances,2)
print(valid_distances)
print(type(valid_distances))

### 3.0.1 Iteración

In [ ]:
 # iterar sobre elementos
for value in fibonacci:
 print('Value: ' + str(value))
# # iterar sobre indices
for index in fibonacci.index:
 print('Index: ' + str(index))

In [ ]:
# iterar sobre elementos e índices al mismo tiempo
for index, value in fibonacci.items():
    print('Index: ' + str(index) + ' Value: ' + str(value))

In [ ]:
for index, value in zip(fibonacci.index, fibonacci):
    print('Index: ' + str(index) + ' Value: ' + str(value))

### 3.1 Series como diccionarios
* Interpretar el índice como clave
* Acepta operaciones para diccionarios

In [ ]:
# crear una serie a partir de un diccionario
serie = pd.Series( { 'Carlos' : 100, 'Marcos': 98} )
print(serie.index)
print(serie.values)
print(serie)
print(type(serie))

In [ ]:
# añade y elimina elementos a través de índices
serie['Pedro'] = 12
serie['Pedro']=15
del serie['Marcos']
print(serie)

In [ ]:
# query una serie
# print(serie['Marcos'])
if 'Marcos' in serie:
    print(serie['Marcos']) #Imprime el valor que tiene no el text
print(serie)

### 3.2 Operaciones entre series

In [ ]:
# suma de dos series
# suma de valores con el mismo índice (NaN si no aparece en ambas)
serie1 = pd.Series([10,20,30,40], index=range(4) )
serie2 = pd.Series([1,2,3], index=range(3) )
suma = serie1 + serie2
print(suma)

In [ ]:
# resta de series (similar a la suma)
print(serie1- serie2)

In [ ]:
# operaciones de pre-filtrado
result = serie1 + serie2
result[pd.isnull(result)] = 0 # mask con isnull()
print(result)

### 3.2.1 Diferencias entre Pandas Series y diccionario
* Diccionario, es una estructura que relaciona las claves y los valores de forma arbitraria.
* Series, estructura de forma estricta listas de valores con listas de índice asignado en la posición.
* Series, es más eficiente para ciertas operaciones que los dicionarios.
* Enlas Series los valores de entrada pueden ser listas o Numpy arrays.
* EnSeries los índices semánticos pueden ser integers o caracteres, en los valores igual.
* Series se podría entender entre una lista y un diccionario Python, pero es de una dimensión
## 4 DataFrame
* Datos tabulares (filas x columnas)
* Columnas: Series con índices compartidos

In [ ]:
# crear un DataFrame a partir de un diccionario de elementos de la misma longitud
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
"Edad" : [34,29,12] }
print(diccionario)
# las claves identifican columnas
frame = pd.DataFrame(diccionario)
display(frame)

In [ ]:
 # crear un DataFrame a partir de un diccionario de elementos de la misma longitud
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
"Edad" : [34,29,12] }
# las claves identifican columnas
frame = pd.DataFrame(diccionario, index = ['a', 'b', 'c'])
display(frame)

In [ ]:
 # además de 'index', el parámetro 'columns' especifica el número y orden de las columnas
frame = pd.DataFrame(diccionario, columns = ['Nacionalidad', 'Nombre', 'Edad','Profesion','Genero'])
display(frame)

In [ ]:
# acceso a columnas
nombres = frame['Nombre']
display(nombres)
print(type(nombres))
edades = frame['Edad']
display(edades)
print(type(edades))

In [ ]:
#siempre que el nombre de la columna lo permita (espacios, ...)
nombres = frame.Profesion
display(nombres)
type(nombres)

In [ ]:
# acceso al primer nombre del DataFrame frame??
print(frame['Nombre'][0])
print(frame.Nombre[0])
print(nombres[0])

### 4.0.1 Formas de crear un DataFrame
* Con una Serie de pandas
* Lista de diccionarios
* Dicionario de Series de Pandas
* Con un array de Numpy de dos dimensiones
* Con array estructurado de Numpy
### 4.1 Modificar DataFrames

In [ ]:
# añadir columnas
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
"Edad" : [34,29,12] }
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre','Edad','Profesion', 'Direccion'])
frame['Direccion'] = 'Desconocida'
display(frame)

In [ ]:
lista_direcciones = ['Rue 13 del Percebe, 13', 'Evergreen Terrace, 3', 'Av de los Rombos, 12']

In [ ]:
frame['Direccion'] = lista_direcciones
display(frame)

In [ ]:
# añadir fila (requiere todos los valores)
user_2 = ['Alemania','Klaus',20, 'none','Desconocida']
frame.loc[3] = user_2
display(frame)

In [ ]:
# eliminar fila (similar a Series)
frame = pd.DataFrame(diccionario,columns=['Nacionalidad', 'Nombre', 'Edad','Profesion'])
frame = frame.drop(2) # por qué necesitamos reasignar el frame?
display(frame)
frame.drop('Nombre', axis = 1, inplace = True)
display(frame)

In [ ]:
#eliminar columna
del frame['Profesion']
display(frame)

In [ ]:
# acceder a la traspuesta (como una matriz)
display(frame.T)

### 4.2 Iteración

In [ ]:
# iteración sobre el DataFrame?
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad','Profesion'])
display(frame)
for a in frame:
    print(a) # qué es 'a'?
    print(type(a))

In [ ]:
# iteracion sobre filas
for value in frame.values:
    print(value)
    print(type(value))

In [ ]:
# iterar sobre filas y luego sobre cada valor?
for values in frame.values:
    for value in values:
        print(value)

### 4.3 Indexación y slicing con DataFrames

In [ ]:
d1 = {'ciudad':'Valencia', 'temperatura':10, 'o2':1}
d2 = {'ciudad':'Barcelona', 'temperatura':8}
d3 = {'ciudad':'Valencia', 'temperatura':9}
d4 = {'ciudad':'Madrid', 'temperatura':10, 'humedad':80}
d5 = {'ciudad':'Sevilla', 'temperatura':15, 'humedad':50, 'co2':6}
d6 = {'ciudad':'Valencia', 'temperatura':10, 'humedad':90, 'co2':10}
ls_data = [d1, d2, d3, d4, d5, d6] # lista de diccionarios
df_data = pd.DataFrame(ls_data, index = list('abcdef'))
display(df_data)

In [ ]:
# Acceso a un valor concreto por indice posicional [row, col]
print(df_data.iloc[1,1])
# Acceso a todos los valores hasta un índice por enteros
display(df_data.iloc[:3,:4])
# Acceso a datos de manera explícita, indice semantico (se incluyen)
display(df_data.loc['a', 'temperatura'])
display(df_data.loc[:'c', :'o2'])
display(df_data.loc[:'c', 'temperatura':'o2'])
display(df_data.loc[:, ['ciudad','o2']])

In [ ]:
# indexación con nombre de columna (por columnas)
print(df_data['ciudad']) #--> Series
display(df_data[['ciudad', 'o2']])

In [ ]:
# indexación con índice posicional (no permitido!). Esto busca columna.
df_data[0]

In [ ]:
 # indexar por posición con 'iloc'
print(df_data.iloc[0]) #--> Series de la primera fila (qué marca los índices)

In [ ]:
#indexar semántico con 'loc'
df_data.loc['a'] #--> Series de la fila con índice 'a'

In [ ]:
 # indexar semántico con 'loc'
df_data.loc[:'b'] #--> DataFrame de la fila con índice 'a' y 'b'

In [ ]:
df_data.loc[:'b'].loc[:,["o2", "humedad"]] # slicing anidado

In [ ]:
 # si se modifica una porcion del dataframe se modifica el dataframe original (referencia)
display(df_data)
serie = df_data.loc['a']
print(serie)
serie.iloc[2] = 3000 # setting with copy warning!!!
display(df_data)
# copiar data frame
df_2 = df_data.loc['a'].copy()
df_2.iloc[2] = 3000
display(df_2)
display(df_data)

In [ ]:
# ambos aceptan 'axis' como argumento
# df_data.iloc(axis=1)[0] #--> todos los valores asignados a la primera␣columna 'ciudad'
df_data.loc(axis=1)['ciudad'] #--> equivalente frame['ciudad']

In [ ]:
# qué problema puede tener este fragmento?
frame = pd.DataFrame({"Name" : ['Carlos','Pedro'], "Age" : [34,22]},index=[1,0])
display(frame)

In [ ]:
# por defecto, pandas interpreta índice posicional--> error en frames
# cuando hay posible ambigüedad, utilizar loc y iloc
print('Primera fila\n')
print(frame.iloc[0])
print('\nElemento con index 0\n')
print(frame.loc[0])

### 4.4 Objeto Index de Pandas

In [ ]:
# Contrucción de índices
ind = pd.Index([2, 3, 5, 23, 26])
# recuperar datos
print(ind[3])
print(ind[::2])

In [ ]:
# usar un objeto index al crear dataframe
frame = pd.DataFrame({"Name" : ['Carlos','Pedro', 'Manolo', 'Luis', 'Alberto'],"Age" : [34,22,15,55,23]}, index=ind)
display(frame)

In [ ]:
 # Son inmutables! No se modifican los datos.
ind[3] = 8

In [ ]:
# change index column
frame = pd.DataFrame({"Name" : ['Carlos','Pedro', 'Manolo', 'Luis', 'Alberto'],"Age" : [34,22,15,55,23]}, index=ind)
display(frame)
frame.set_index('Age', inplace=True)
display(frame)

### 4.5 Slicing

In [ ]:
# slice por filas
d_and_d_characters = {'Name' : ['bundenth','theorin','barlok'], 'Strength' :[10,12,19], 'Wisdom' : [20,13,6]}
character_data = pd.DataFrame(d_and_d_characters, index=['a','b','c'])
display(character_data)
display(character_data[:-1])
display(character_data[1:2])

In [ ]:
# slicing para columnas
display(character_data[['Name','Wisdom']])

In [ ]:
#slicing con 'loc' e 'iloc'
display(character_data.iloc[1:])
display(character_data.loc[:'b','Name':'Strength'])

¿Cómo filtrar filas y columnas? Por ejemplo, para todos los personajes, obtener ‘Name’ y ‘Strength’

In [ ]:
# usando 'loc' para hacer slicing
display(character_data.loc[:,'Name':'Strength'])

In [ ]:
# usando 'loc' para buscar específicamente filas y columnas
display(character_data.loc[ ['a','c'], ['Name','Wisdom'] ])

In [ ]:
# lo mismo con 'iloc'?
display(character_data.iloc[[0,2],[0,2]])
display(character_data.iloc[[0,-1],[0,-1]])

In [ ]:
# lista de los personajes con el atributo Strength > 11
# Verificando que el nombre coincida exactamente con lo que imprimiste arriba
display(character_data.loc[character_data['Strength'] > 11, ['Name', 'Strength']])

In [ ]:
# listar los personajes con Strength > 15 o Wisdom > 15
display(character_data.loc[(character_data['Strength'] > 15) |(character_data['Wisdom'] > 15)])

## 5 Cargar y guardar datos en pandas

In [ ]:
 # Guardar a csv
import os
ruta = os.path.join("res" ,"o_d_d_characters.csv")
#character_data.to_csv(ruta, sep=';') # sep por defecto: ','

In [ ]:
loaded = pd.read_csv(ruta, sep=';')
display(loaded)

In [ ]:
ruta = os.path.join("res","titanic.csv")

In [ ]:
titanic = pd.read_csv(ruta, sep=',')
display(titanic)

In [ ]:
loaded = pd.read_csv(ruta, sep=',', index_col = 0)
display(loaded)

**otros argumentos to_csv()**
*  na_rep=‘string’–> representar valores NaN en el archivo csv<br>
**otros argumentos read_csv()**
* na_values=‘string’<br>
Pandas también ofrece funciones para leer/guardar a otros formatos estándares: JSON, HDF5 o
Excel en su [API](https://pandas.pydata.org/pandas-docs/stable/reference/io.html)

## 6 Ejemplo práctico en pandas
* MovieLens dataset
* Reviews de películas
* 1 millón de entradas
* Datos demográficos de usuarios

In [1]:
import numpy as np
import pandas as pd
import zipfile # para descomprimir archivos zip
import urllib.request # para descargar de URL
import os
# descargar MovieLens dataset
url = 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'
ruta = os.path.join("res", "ml-1m.zip")
urllib.request.urlretrieve(url, ruta)

('res\\ml-1m.zip', <http.client.HTTPMessage at 0x263d25f8c30>)

In [3]:
# descomprimiendo archivo zip
ruta_ext = os.path.join("res")
with zipfile.ZipFile(ruta, 'r') as z:
    print('Extracting all files...')
    z.extractall(ruta_ext) # destino
    print('Done!')
# take a look at readme y revisar formatos

Extracting all files...
Done!

In [4]:
ruta_users = os.path.join("res", "ml-1m", "users.dat")
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0, engine='python')
display(users_dataset)

      F  1.1  10  48067
1
2     M   56  16  70072
3     M   25  15  55117
4     M   45   7  02460
5     M   25  20  55455
6     F   50   9  55117
...  ..  ...  ..    ...
6036  F   25  15  32603
6037  F   45   1  76006
6038  F   56   1  14706
6039  F   45   0  01060
6040  M   25   6  11106

[6039 rows x 4 columns]

In [5]:
# Varios problemas
# sin cabecera! primer valor se ha perdido
# las columnas no tienen nombres
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Character or regex pattern to treat as the delimiter. If ``sep=None``, the
    C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator from only the first valid
    row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
    In addition, separators longer than 1 character and different from
    ``'\s+'`` will be interpreted as regular expressions and will also force
    the use of the Python parsing engine. Note that regex delimiters are prone
    to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, optional
    Alias for ``sep``.
header : int, Sequence of int, 'infer' or None, default 'infer'
    Row number(s) containing column labels and marking the start of the
    data (zero-indexed). Default behavior is to infer the column names: if no ``names``
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly to ``names`` then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a :class:`~pandas.MultiIndex` on the columns
    e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : Sequence of Hashable, optional
    Sequence of column labels to apply. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : Hashable, Sequence of Hashable or False, optional
  Column(s) to use as row label(s), denoted either by column labels or column
  indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
  will be formed for the row labels.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g., when you have a malformed file with delimiters at
  the end of each line.
usecols : Sequence of Hashable or Callable, optional
    Subset of columns to select, denoted either by column labels or column indices.
    If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in ``names`` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
    preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
    for columns in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to ``True``. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : dtype or dict of {Hashable : dtype}, optional
    Data type(s) to apply to either the whole dataset or individual columns.
    E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
    Use ``str`` or ``object`` together with suitable ``na_values`` settings
    to preserve and not interpret ``dtype``.
    If ``converters`` are specified, they will be applied INSTEAD
    of ``dtype`` conversion.

    .. versionadded:: 1.5.0

        Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
        the default determines the ``dtype`` of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The 'pyarrow' engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict of {Hashable : Callable}, optional
    Functions for converting values in specified columns. Keys can either
    be column labels or column indices.
true_values : list, optional
    Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
false_values : list, optional
    Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : int, list of int or Callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (``int``)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
    Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
    per-column ``NA`` values.  By default the following values are interpreted as
    ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
    "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
    "n/a", "nan", "null ".

keep_default_na : bool, default True
    Whether or not to include the default ``NaN`` values when parsing the data.
    Depending on whether ``na_values`` is passed in, the behavior is as follows:

    * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
      is appended to the default ``NaN`` values used for parsing.
    * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
      the default ``NaN`` values are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
      the ``NaN`` values specified ``na_values`` are used for parsing.
    * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
      strings will be parsed as ``NaN``.

    Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
    ``na_values`` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of ``na_values``). In
    data without any ``NA`` values, passing ``na_filter=False`` can improve the
    performance of reading a large file.
verbose : bool, default False
    Indicate number of ``NA`` values placed in non-numeric columns.

    .. deprecated:: 2.2.0
skip_blank_lines : bool, default True
    If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
    The behavior is as follows:

    * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
      ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
    * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
      each as a separate date column.
    * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
      as a single date column. Values are joined with a space before parsing.
    * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
      result 'foo'. Values are joined with a space before parsing.

    If a column or index cannot be represented as an array of ``datetime``,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an ``object`` data type. For
    non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
    :func:`~pandas.read_csv`.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
    format of the ``datetime`` strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If ``True`` and ``parse_dates`` specifies combining multiple columns then
    keep the original columns.
date_parser : Callable, optional
    Function to use for converting a sequence of string columns to an array of
    ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. pandas will try to call ``date_parser`` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by ``parse_dates`` into a single array
    and pass that; and 3) call ``date_parser`` once for each row using one or
    more strings (corresponding to the columns defined by ``parse_dates``) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`~pandas.to_datetime` as-needed.
date_format : str or dict of column -> format, optional
    Format to use for parsing dates when used in conjunction with ``parse_dates``.
    The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
    `strftime documentation
    <https://docs.python.org/3/library/datetime.html
    #strftime-and-strptime-behavior>`_ for more information on choices, though
    note that :const:`"%f"` will parse all the way up to nanoseconds.
    You can also pass:

    - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
        time string (not necessarily in exactly the same format);
    - "mixed", to infer the format for each element individually. This is risky,
        and you should probably use it along with `dayfirst`.

    .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If ``True``, use a cache of unique, converted dates to apply the ``datetime``
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return ``TextFileReader`` object for iteration or getting chunks with
    ``get_chunk()``.
chunksize : int, optional
    Number of lines to read from the file per chunk. Passing a value will cause the
    function to return a ``TextFileReader`` object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str (length 1), optional
    Character acting as the thousands separator in numerical values.
decimal : str (length 1), default '.'
    Character to recognize as decimal point (e.g., use ',' for European data).
lineterminator : str (length 1), optional
    Character used to denote a line break. Only valid with C parser.
quotechar : str (length 1), optional
    Character used to denote the start and end of a quoted item. Quoted
    items can include the ``delimiter`` and it will be ignored.
quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
    ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
    characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
    or ``lineterminator``.
doublequote : bool, default True
   When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    Character used to escape other characters.
comment : str (length 1), optional
    Character indicating that the remainder of line should not be parsed.
    If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter ``header`` but not by
    ``skiprows``. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
    treated as the header.
encoding : str, optional, default 'utf-8'
    Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

encoding_errors : str, optional, default 'strict'
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
    ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
    override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

    - ``'error'``, raise an Exception when a bad line is encountered.
    - ``'warn'``, raise a warning when a bad line is encountered and skip that line.
    - ``'skip'``, skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - Callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new ``list`` of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine='python'``

    .. versionchanged:: 2.2.0

        - Callable, function with signature
          as described in `pyarrow documentation
          <https://arrow.apache.org/docs/python/generated/pyarrow.csv.ParseOptions.html
          #pyarrow.csv.ParseOptions.invalid_row_handler>`_ when ``engine='pyarrow'``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'\t'``) will be

In [6]:
# especificar nombres, cargar sin cabecera
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],engine='python')
display(users_dataset)

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460
5           M   25          20    55455
...       ...  ...         ...      ...
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

[6040 rows x 4 columns]

In [7]:
# samplear la tabla
display(users_dataset.sample(10))

       Gender  Age  Occupation Zip-code
UserID
4058        M   25           6    73118
5317        F   25           0    02138
5010        M   45          15    63119
4015        F   45           3    75605
1916        M   45           7    90405
2702        M   45           6    65201
4779        M   45           3    04011
2789        M   18           4    90025
186         M   18           5    91767
3269        F   18          20    45220

In [8]:
# samplear la cabeza
display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460

In [9]:
# samplear la cola
display(users_dataset.tail(10))

       Gender  Age  Occupation Zip-code
UserID
6031        F   18           0    45123
6032        M   45           7    55108
6033        M   50          13    78232
6034        M   25          14    94117
6035        F   25           1    78734
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

In [10]:
# tipos de datos sobre las columnas
users_dataset.dtypes

Gender        object
Age            int64
Occupation     int64
Zip-code      object
dtype: object

In [11]:
 display(users_dataset[users_dataset['Zip-code'].str.len() > 5])

       Gender  Age  Occupation    Zip-code
UserID
161         M   45          16  98107-2117
233         F   45          20  37919-4204
293         M   56           1  55337-4056
458         M   50          16  55405-2546
506         M   25          16  55103-1006
...       ...  ...         ...         ...
5682        M   18           0  23455-4959
5904        F   45          12      954025
5925        F   25           0  90035-4444
5967        M   50          16  73069-5429
5985        F   18           4  78705-5221

[81 rows x 4 columns]

In [12]:
# información general sobre atributos numéricos
display(users_dataset.describe())

               Age   Occupation
count  6040.000000  6040.000000
mean     30.639238     8.146854
std      12.895962     6.329511
min       1.000000     0.000000
25%      25.000000     3.000000
50%      25.000000     7.000000
75%      35.000000    14.000000
max      56.000000    20.000000

In [13]:
# información general sobre atributos numéricos
display(users_dataset.describe())

               Age   Occupation
count  6040.000000  6040.000000
mean     30.639238     8.146854
std      12.895962     6.329511
min       1.000000     0.000000
25%      25.000000     3.000000
50%      25.000000     7.000000
75%      35.000000    14.000000
max      56.000000    20.000000

In [14]:
# incluir otros atributos (no todo tiene sentido)
display(users_dataset.describe(include='all'))

       Gender          Age   Occupation Zip-code
count    6040  6040.000000  6040.000000     6040
unique      2          NaN          NaN     3439
top         M          NaN          NaN    48104
freq     4331          NaN          NaN       19
mean      NaN    30.639238     8.146854      NaN
std       NaN    12.895962     6.329511      NaN
min       NaN     1.000000     0.000000      NaN
25%       NaN    25.000000     3.000000      NaN
50%       NaN    25.000000     7.000000      NaN
75%       NaN    35.000000    14.000000      NaN
max       NaN    56.000000    20.000000      NaN

In [15]:
# cuántos usuarios son mujeres (Gender='F')
len(users_dataset[users_dataset['Gender'] == 'F'])
#select count(*) from users_dataset where users_dataset.Gender = 'F'

1709

In [16]:
# mostrar solo los menores de edad
under_age = users_dataset[users_dataset['Age'] == 1]
print(len(under_age))
display(under_age.sample(10))

222

       Gender  Age  Occupation Zip-code
UserID
2133        F    1          10    01607
2217        M    1          10    44906
829         M    1          19    53711
1182        M    1          10    91326
1263        M    1          10    81301
5637        M    1          10    11102
1563        F    1          10    87123
1096        M    1          10    80439
484         F    1          10    55104
719         M    1           0    75070

In [17]:
# filtrar edad incorrecta (míninimo 18) SettingWithCopyWarning!!!
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],engine='python')
under_age = users_dataset[users_dataset['Age'] == 1]
under_age.loc['Age'] = np.nan
display(under_age.head())
users_dataset[users_dataset['Age'] < 18] = under_age
display(users_dataset)

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_1316\851287154.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  under_age.loc['Age'] = np.nan

       Gender  Age  Occupation Zip-code
UserID
1           F  1.0        10.0    48067
19          M  1.0        10.0    48073
51          F  1.0        10.0    10562
75          F  1.0        10.0    01748
86          F  1.0        10.0    54467

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460
5           M   25          20    55455
...       ...  ...         ...      ...
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

[6040 rows x 4 columns]

In [19]:
# filtrar edad incorrecta (míninimo 18) Fixing it by Copying the slice
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],engine='python')
under_age = users_dataset[users_dataset['Age'] == 1]
under_age_copy = under_age.copy()
display(under_age_copy.head())
under_age_copy['Age'] = np.nan
display(under_age_copy.head())
users_dataset[users_dataset['Age'] == 1] = under_age_copy # sets the rows according to the indexes
display(users_dataset.head())

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748
86          F    1          10    54467

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748
86          F  NaN          10    54467

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [20]:
# filtrar edad incorrecta (míninimo 18) Remove them from the dataset
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],engine='python')
display(users_dataset[users_dataset['Age'] == 1].head(4))
users_dataset.loc[users_dataset['Age'] == 1, 'Age'] = np.nan
display(users_dataset)
display(users_dataset.loc[pd.isnull(users_dataset['Age'])].head(4))
users_dataset.drop(users_dataset[pd.isnull(users_dataset['Age'])].index,inplace = True)
display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455
...       ...   ...         ...      ...
6036        F  25.0          15    32603
6037        F  45.0           1    76006
6038        F  56.0           1    14706
6039        F  45.0           0    01060
6040        M  25.0           6    11106

[6040 rows x 4 columns]

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748

       Gender   Age  Occupation Zip-code
UserID
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [21]:
# Agrupar datos por atributos
display(users_dataset.groupby(by='Gender').describe())

           Age                                                     Occupation  \
         count       mean        std   min   25%   50%   75%   max      count
Gender
F       1631.0  32.287554  11.792015  18.0  25.0  25.0  45.0  56.0     1631.0
M       4187.0  31.568665  11.716053  18.0  25.0  25.0  35.0  56.0     4187.0


            mean       std  min  25%  50%   75%   max
Gender
F       6.498467  5.960285  0.0  1.0  4.0  11.0  20.0
M       8.743253  6.441753  0.0  4.0  7.0  15.0  20.0

In [22]:
# Grabar la tabla modificada
# Cambiar el separador a ','
# Guardar NaN como 'null'
ruta_output = os.path.join('res', 'ml-1m', 'o_users_processed.csv')
users_dataset.to_csv(ruta_output, sep=',',na_rep='null')

## 7 Ejercicios
* Hacer un análisis general de los otros dos archivos CSV en ml-1m (‘movies.dat’ y ‘ratings.dat’)
* Analizando el dataset ratings.dat, ¿hay algún usuario que no tenga ninguna review? ¿Cuántos tienen menos de 30 reviews?

#### 7.1. Carga y Análisis General
* Para empezar, se necesita cargar los datos correctamente:

In [25]:
# Definir rutas
ruta_movies = os.path.join("res", "ml-1m", "movies.dat")
ruta_ratings = os.path.join("res", "ml-1m", "ratings.dat")

# Cargar archivos
movies = pd.read_csv(ruta_movies, sep='::', header=None, names=['MovieID', 'Title', 'Genres'], engine='python', encoding='latin-1')
ratings = pd.read_csv(ruta_ratings, sep='::', header=None, names=['UserID', 'MovieID', 'Rating', 'Timestamp'], engine='python')

print(f"Total de películas: {len(movies)}")
print(f"Total de calificaciones: {len(ratings)}")

Total de películas: 3883
Total de calificaciones: 1000209

#### 7.2. Análisis de ratings.dat
Para responder a a la pregunta, usamos la función groupby sobre el UserID.

¿Hay algún usuario que no tenga ninguna review?
Respuesta corta: No. En este dataset específico (ml-1m), por diseño, solo aparecen los usuarios que han realizado al menos 20 calificaciones. Si un usuario no tiene reviews, simplemente no figura en el archivo ratings.dat. Sin embargo, si quisieras comprobarlo cruzándolo con el archivo de usuarios (users.dat), podrías buscar IDs de usuarios que estén en "users" pero no en "ratings".

¿Cuántos tienen menos de 30 reviews?
* Para esto, cuenta cuántas veces aparece cada UserID y filtra:

In [27]:
# Contar reviews por usuario
reviews_por_usuario = ratings.groupby('UserID').size()

# Filtrar los que tienen menos de 30
usuarios_menos_30 = reviews_por_usuario[reviews_por_usuario < 30]

print(f"Cantidad de usuarios con menos de 30 reviews: {len(usuarios_menos_30)}")

Cantidad de usuarios con menos de 30 reviews: 751

In [ ]:
https://github.com/emev0417/python2026/blob/main/pandas1.ipynb